/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {}
  interface TmDatePicker {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLTmDatePickerElement extends Components.TmDatePicker, HTMLStencilElement {}
  var HTMLTmDatePickerElement: {
    prototype: HTMLTmDatePickerElement;
    new (): HTMLTmDatePickerElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'tm-date-picker': HTMLTmDatePickerElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {}
  interface TmDatePicker {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'tm-date-picker': TmDatePicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'tm-date-picker': LocalJSX.TmDatePicker & JSXBase.HTMLAttributes<HTMLTmDatePickerElement>;
    }
  }
}


